### PR TITLE
Add image path validation for open documents

### PR DESCRIPTION
**Pull request by rnathuji**
This PR builds on the branch with [language server setup](https://github.com/openstax/poet/pull/12). ~~The relative additions can be viewed using [this comparison](https://github.com/openstax/poet/compare/cnx1428/add-language-server..cnx1355/image-path-validation) until the base PR is merged.~~

### CODE REVIEW

**Comment by c0ldcalamari** [comment]
@ripal I'm not familiar with node, but I was trying to run the test for this PR, does this [line](https://github.com/openstax/poet/blob/cnx1355/image-path-validation/package.json#L23) need to be updated?

**Comment by c0ldcalamari** [comment]
@ripal how do I get/ generate the `./server/out/test/server.test.js` file?

```
error 1 [Mon Feb 22 13:06:40]brenda@brenda-openstax:poet[cnx1355/image-path-validation] $ npm run test-server

> editor@0.0.0-dev test-server /Users/brenda/Projects/00_openstax/poet
> ./server/node_modules/.bin/mocha ./server/out/test/server.test.js

Error: No test files found: "./server/out/test/server.test.js"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! editor@0.0.0-dev test-server: `./server/node_modules/.bin/mocha ./server/out/test/server.test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the editor@0.0.0-dev test-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brenda/.npm/_logs/2021-02-22T19_06_45_126Z-debug.log

```

**Comment by rnathuji** [comment]
@c0ldcalamari - Ah, documentation miss on my part. I just added [some content](https://github.com/openstax/poet/pull/17/commits/94f24659002428a981b6765470bba51078a7665a) to the `README.md` with how to run them.

**Comment by c0ldcalamari** [comment]
@rnathuji awesome, thank you!

**Review by c0ldcalamari — APPROVED** [review]

**Comment by c0ldcalamari** [comment]
Reviewed: No further questions.

**Pull request merged**
