### PR TITLE
Make md:title optional in patch file

### PR DESCRIPTION
**Pull request by TylerZeroMaster**
part of openstax/ce#1528

It's already optional in the unpatched schema.

### CODE REVIEW

**Review by philschatz — APPROVED** [review]
:+1:

**Comment by TylerZeroMaster** [comment]
(writing test cases on the PR instead of this issue this time because the issue has more criteria)

# md:title should now be optional
## GIVEN
- This [version](https://github.com/openstax/poet/actions/runs/9501775104/artifacts/1598508053) of POET (editor-0.0.0-dev-199)
- A book repository fully loaded in POET
## WHEN
- The `md:title` is removed from a module's metadata
## THEN
- There are no validation errors

---

# Document title should still be required
## GIVEN
- This [version](https://github.com/openstax/poet/actions/runs/9501775104/artifacts/1598508053) of POET (editor-0.0.0-dev-199)
- A book repository fully loaded in POET
## WHEN
- The `title` is removed from a module
## THEN
- There are validation errors

**Comment by omehes** [comment]
verified in editor-0.0.0-dev-199.vsix
corgi job (without md:title) 
looks good

**Comment by omehes** [comment]
verified in poet ext 7.0.0.

**Pull request merged**
