### PR TITLE
Update schema with new 'noindex' document attribute

### PR DESCRIPTION
**Pull request by TylerZeroMaster**
part of openstax/ce#2240

Update schema to allow `noindex` attribute on `document`

### CODE REVIEW

**Review by sparksam — APPROVED** [review]
Looks good to me

**Comment by TylerZeroMaster** [comment]
# `noindex` attribute is optional
## GIVEN
- A book repository
- Version [editor-0.0.0-dev-200](https://github.com/openstax/poet/actions/runs/9650928562/artifacts/1633045044) POET
## WHEN
- A `document` element does not have a `noindex` attribute
## THEN
- There are no validation errors

---

# `noindex` attribute only supports values `true` and `false`
## GIVEN
- A book repository
- Version [editor-0.0.0-dev-200](https://github.com/openstax/poet/actions/runs/9650928562/artifacts/1633045044) POET
## WHEN
- The `noindex` attribute is added to the `document` element in a module
- The value of the attribute is set to anything other than `"true"` or `"false"` (Known issue: whitespace is ignored during validation so values like `"true    "` will also be valid)
## THEN
- There are validation errors related to xml schema

---

# `noindex` attribute is only supported on document element
## GIVEN
- A book repository
- Version [editor-0.0.0-dev-200](https://github.com/openstax/poet/actions/runs/9650928562/artifacts/1633045044) POET
## WHEN
- The `noindex` attribute is added to anything other than a `document` element with a value of `"true"` or `"false"`
## THEN
- There are validation errors related to xml schema

**Comment by omehes** [comment]
all tests passed. looks good with the dev extension provided

**Comment by omehes** [comment]
verified in poet ext. 7.0.0

**Pull request merged**
