### PR TITLE
:fire: remove git-history-plus

### PR DESCRIPTION
**Pull request by philschatz**
because that extension does not exist in the vscode marketplace.

This makes it possible for people to install the extension from the VSCode marketplace

### CODE REVIEW

**Comment by m1yag1** [comment]
@ckline-tryptic suggested this plugin that is available on the marketplace. https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph

**Comment by m1yag1** [comment]
**Reminder** When we remove this extension we need to remove the button.

**Comment by TylerZeroMaster** [comment]
It also might be worth noting that [donjayamanne.githistory](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory) is on both marketplaces and has the exact same commands as git history plus. This could be an easy drop-in replacement if we want to go that route.

**Comment by ne-newton** [comment]
I have confirmed with CMs: none of them have used this, so it can safely be removed, along with the button.

**Review by sparksam — APPROVED** [review]

**Review by ckline-tryptic — APPROVED** [review]

**Review by therealmarv — APPROVED** [review]

**Pull request merged**
